### ISSUE TITLE
npm Readme

### ISSUE THREAD

**Issue by MiXT4PE** [coderaiser/smalltalk#12]
The [npm Readme](https://www.npmjs.com/package/smalltalk) states multiple flawed examples:

    smalltalk
        .prompt('Question', 'How old are you?', '10')
        .then((value) => {
            console.log(value);
        .catch(() => {
            console.log('cancel');
        });

or

    smalltalk
        .confirm('Question', 'Are you sure?')
        .then(() => {
            console.log('yes');
        .catch(() => {
            console.log('no');
        });

Both times the closing brackets `})` of the `.then` are not placed. Not sure if this is the correct way to tell you this but I figured this should be fixed.

**Comment by coderaiser** [comment]
It is already fixed with 08f0c35 and will be in npm with next release.
