### ISSUE TITLE
Double quotes in value of prompt() can't be shown

### ISSUE THREAD

**Issue by towerpark** [coderaiser/smalltalk#2]
If the "value" parameter of prompt() contains double quotes, the string is cut at the first double quote.
E.g. the code below only shows 'a'.
`smalltalk.prompt('hello', 'world', 'a"b"c').then(function(value) {}, function() {});`

<img width="318" alt="prompt" src="https://cloud.githubusercontent.com/assets/24645162/23213405/1d436f6e-f94e-11e6-803e-b73c0264837f.png">

It seems that double quotes aren't being escaped.

**Comment by coderaiser** [comment]
Thank you, fixed with f68cfec. Landed in [v2.1.4](https://github.com/coderaiser/smalltalk/releases/tag/v2.1.4).

**Comment by towerpark** [comment]
Just updated to the newest version.
Thank you for the quick response   :)
