### ISSUE TITLE
smalltalk.min.js for in browser script tag

### ISSUE THREAD

**Issue by ray73864** [coderaiser/smalltalk#22]
Was wondering where I can get a pre-built minified version of this for use in a browser script tag?

I have checked several CDNs and the only one I found complains about require(), have checked 'npm i smalltalk' but there is no smalltalk.min.js file available, cloned this repository but couldn't figure out how to create the necessary stuff.

**Comment by coderaiser** [comment]
Good point, thank you :), just added ability to upload assets to [releases page](https://github.com/coderaiser/smalltalk/releases) on every new version of `smalltalk`.

**Comment by ray73864** [comment]
Awesome, thankyou for that. 

Though I do notice there are a lot of comments in the minified file which increase its file size unnecessarily.

**Comment by coderaiser** [comment]
This is a very good point :), just updated assets.
