### ISSUE TITLE
An error when using smalltalk with Electron

### ISSUE THREAD

**Issue by EnderCommunity** [coderaiser/smalltalk#26]
![Error 4_14_2020 6_22_26 PM](https://user-images.githubusercontent.com/57331033/79243249-0c908b80-7e7e-11ea-9339-87fbed71b139.png)

**Comment by EnderAdel** [comment]
These are *smalltalk*'s module files:
![smalltalk 4_14_2020 6_32_19 PM](https://user-images.githubusercontent.com/57331033/79243520-64c78d80-7e7e-11ea-88cd-cef6bc484863.png)

**Comment by coderaiser** [comment]
You should use [bundled version](https://github.com/coderaiser/smalltalk/releases/tag/v4.0.6) with electron, or setup build process with `webpack` :). Is it helps?

**Comment by EnderAdel** [comment]
Can you tell me how can I install the bundled version? please

**Comment by coderaiser** [comment]
@EnderAdel you can’t install bundled version, you can only download it from releases page. Anyways you can add `webpack` to your setup, and build it for yourself using [webpack.config.js](https://github.com/coderaiser/smalltalk/blob/master/webpack.config.js) as an example. If you don’t use build system, I suggest you to add it for such case as the need of reuse some components of your application in the browser or node.js :).

**Comment by EnderAdel** [comment]
it didn't work

**Comment by coderaiser** [comment]
Could you please provide error message you have?

**Comment by LucasArgate** [comment]
+1

im having the same error, do you have something new @EnderCommunity ?

**Comment by coderaiser** [comment]
Use:

```js
import smalltalk from 'smalltak/bundle';
```

or 
```js
const smalltalk = require('smalltalk/bundle');
```

Since [v4.1.0](https://github.com/coderaiser/smalltalk/releases/tag/v4.1.0)

Is it works for you?
