### ISSUE TITLE
No way to customize buttons in Progress

### ISSUE THREAD

**Issue by girobusan** [coderaiser/smalltalk#29]
Now progress does not use options object at all, and so you can not customize buttons, or remove them (which would be useful for progress widget)

**Comment by coderaiser** [comment]
That's a good idea for a pull request :).

**Comment by girobusan** [comment]
I know, how to fix it, but I've never done pull requests befor

**Comment by coderaiser** [comment]
You can write here your ideas, it will speed things up :).
