### ISSUE TITLE
Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by dfcreative** [coderaiser/smalltalk#3]
Hi!
Installed plugin and tried to use, but got
```
Couldn't find preset "es2015" relative to directory "C:\\projects\\rage-game\\node_modules\\smalltalk" while parsing file: C:\projects\rage-game\node_modules\smalltalk\lib\smalltalk.js
```
No idea why it does not work by default.

**Comment by coderaiser** [comment]
What are you use for building? Is it `webpack`? Can you show me config?

**Comment by coderaiser** [comment]
Also you can try:

```js
const smalltalk = require('smalltalk/legacy');
```

To  use transpiled version of `smalltalk`.

**Comment by dfcreative** [comment]
I use browserify. Switched to [dialogs](https://npmjs.org/package/dialogs) for now.
