### ISSUE TITLE
works, but does not open in new window, just sets HTML at the bottom of screen

### ISSUE THREAD

**Issue by alandoyle95** [coderaiser/smalltalk#4]
all the prompt stuff works but it gets added to the bottom of the screen and not into a new window?

**Comment by coderaiser** [comment]
What browser, and what version of a browser are you using?

**Comment by alandoyle95** [comment]
Electron latest version.

**Comment by coderaiser** [comment]
Actually `smalltalk` should not open new window, it is creates modal window inside webpage similar to ones used in `chrome`.

Could you show me screenshot?

**Comment by alandoyle95** [comment]
Yea in about 5 hours when I get to work.. if I'm not half asleep.. xD it is
in the renderer process if that makes any difference

On Aug 9, 2017 12:04 AM, "coderaiser" <notifications@github.com> wrote:

Actually smalltalk should not open new window, it is creates modal window
inside webpage similar to ones used in chrome.

Could you show me screenshot?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/coderaiser/smalltalk/issues/4#issuecomment-321171603>,
or mute the thread

**Comment by coderaiser** [comment]
Closed due to lack of information.

**Comment by solancer** [comment]
This is happening in the latest install of electron. It doesn't matter if I call it in the renderer or the main window through IRPC its the same.

PFA screenshot below.

![screen shot 2017-08-10 at 9 24 10 pm](https://user-images.githubusercontent.com/800668/29179559-65d22222-7e12-11e7-94fe-dc76327bd9db.png)

**Comment by alandoyle95** [comment]
OK, sorry work has been EXTREMELY crazy lately...  the above screen shot is exactly what its doing except i was using the prompt as well.
