### ISSUE TITLE
just sets HTML at the bottom of screen

### ISSUE THREAD

**Issue by solancer** [coderaiser/smalltalk#6]
This is happening in the latest install of electron. It doesn't matter if I call it in the renderer or the main window through IRPC its the same.

same as #4 

PFA screenshot below.

![screen shot 2017-08-10 at 9 24 10 pm](https://user-images.githubusercontent.com/800668/29179624-ac919756-7e12-11e7-97f3-1faa478e3af2.png)

**Comment by coderaiser** [comment]
Related to #4.

Did you add `dist/smalltalk.css` to your `html page` like in [example](https://github.com/coderaiser/smalltalk/blob/068c97d975dc0059b24660459afeb90dfc6555bb/example/index.html)?

**Comment by coderaiser** [comment]
Close due to long time of inactivity
